# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: akali <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/08/11 14:06:51 by akali             #+#    #+#              #
#    Updated: 2018/08/11 16:11:47 by jcope            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = colle-2
SRCS = rush_2.c utility.c
RSRCS = ft_atoi.c main.c ft_putchar.c
INCLUDE = ./include
FLAG = -Wall -Werror -Wextra


all:
	gcc $(SRCS) -Wall -Werror -Wextra -o $(NAME) -I $(INCLUDE) 
	gcc $(RSRCS) rush00.c $(FLAG) -o colle-00	
	gcc $(RSRCS) rush01.c $(FLAG) -o colle-01
	gcc $(RSRCS) rush02.c $(FLAG) -o colle-02
	gcc $(RSRCS) rush03.c $(FLAG) -o colle-03
	gcc $(RSRCS) rush04.c $(FLAG) -o colle-04
	
clean:

fclean:


